// <auto-generated />
namespace RazorCars.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class RentalHistoryAdded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RentalHistoryAdded));
        
        string IMigrationMetadata.Id
        {
            get { return "201512212038300_RentalHistoryAdded"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
